name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harshasridhar/Taxi_Fare_prediction@main # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nyc-tlc-taxi-fare-prediction" #Must be unique in Heroku
          heroku_email: "sridharsha598@gmail.com"
          usedocker: true
        env:
          API_KEY: ${{secrets.API_KEY}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
